targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake # Converts camelCase to snake_case in JSON
          checked: true # Enables runtime validation
          explicit_to_json: true # Calls `toJson` explicitly for nested objects
